server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seed?characterEncoding=utf8&ssl=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: true
    encoding: utf-8
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.spring.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  config: classpath:logback-spring.xml
